### ISSUE TITLE
启用 Firefox `增强型追踪保护` 导致无法正常加载图片

### ISSUE THREAD

**Issue by pizeroLOL** [YidaozhanYa/blog#16]
开启增强型追踪保护

![浏览器](https://github.com/chiyuki0325/blog/assets/71167373/cbc10581-5f7a-403a-ba55-c6fe180190e7)

关闭后显示效果

![图片](https://github.com/chiyuki0325/blog/assets/71167373/982eec34-bfb7-488d-af21-819158f41f35)

**Comment by chiyuki0325** [comment]
目前博客的图片存在了百度贴吧的图床上，可能贴吧的域名被火狐判定为追踪器了。等我的身份允许后会自行购买合法图床，抱歉带来不好的访问体验。

**Comment by chiyuki0325** [comment]
图床已迁移到 Cloudflare R2
